services:
  web1:
    container_name: web1
    image: web1
    ports:
      - "8081:8080"
    build:
      context: web1
    networks:
      site-2-net:
        ipv4_address: 172.19.0.3
  web2:
    container_name: web2
    image: web2
    ports:
      - "8082:8080"
    build:
      context: web2
    networks:
      site-2-net:
        ipv4_address: 172.19.0.4
  nginx2:
    container_name: nginx2
    image: nginx2
    ports:
      - "443:443"
    build:
      context: nginx2
    networks:
      site-2-net:
        ipv4_address: 172.19.0.2
networks:
  site-2-net:
    name: site-2-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

